### ISSUE TITLE
Substitution key hint shows even when a sub is used

### ISSUE THREAD

**Issue by colleenmcginnis** [elastic/docs-builder#779]
### Describe the bug

I'm seeing hints suggesting that a substitution key is not used when it is used in one or more Markdown files.

Note: In the example I provided below, the Markdown file where the variables are used also use page-level subs in the frontmatter. I'm not sure if that could be the cause.

### Expected behavior

I should only get hints when a substitution key is actually not used.

### Steps to reproduce

Here's an example:

1. The [build for apm-agent-nodejs](https://github.com/elastic/apm-agent-nodejs/actions/runs/13951128526/job/39050658323#step:11:38) shows two hints:
    ```
    Hint: Substitution key 'ecloud' is not used in any file
    NOTE: /github/workspace/docs/docset.yml
     
    Hint: Substitution key 'apm-lambda-ext' is not used in any file
    NOTE: /github/workspace/docs/docset.yml
    ```
2. But when I check for usage of those subs, I find uses:
    * `{{ecloud}}`: https://github.com/elastic/apm-agent-nodejs/blob/main/docs/reference/lambda.md?plain=1#L21
    * `{{apm-lambda-ext}}`: https://github.com/elastic/apm-agent-nodejs/blob/main/docs/reference/lambda.md?plain=1#L25

### Tooling

- [x] docs-builder
- [ ] migration tooling
- [ ] I'm not sure

**Comment by shainaraskas** [comment]
> Note: In the example I provided below, the Markdown file where the variables are used also use page-level subs in the frontmatter. I'm not sure if that could be the cause.

I'm seeing this in pages where there are no front matter keys set

**Comment by Mpdreamz** [comment]
Forgot one line in the one place we parse variables 😸 

https://github.com/elastic/docs-builder/pull/809 should fix this.

**Comment by colleenmcginnis** [comment]
Thank you! I'm still seeing a few problems 😬  https://github.com/elastic/docs-builder/issues/814.
